# This file is part of tdm-launcher.
# Copyright 2022 ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE,
# Miniature Mobile Robots group, Switzerland
# Author: Yves Piguet

SRC = tdmlauncher.swift

tdmlauncher: $(SRC)
	swiftc -o $@ $^
